name: flutter_portfolio_web

dependencies:
  flutter:
    sdk: flutter

  # The following dependencies are commonly used for Flutter web applications.
  flutter_web_plugins:
  http:
  provider:
  flutter_svg:
  url_launcher:

dev_dependencies:
  build_runner:
  build_web_compilers:
